# Generated by Django 6.0 on 2025-12-05 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_keyword', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('vendor', 'Vendor'), ('os', 'Operating System'), ('cpu', 'CPU'), ('platform', 'Platform'), ('environment', 'Environment'), ('accelerator', 'Accelerator'), ('NIC', 'NIC'), ('other', 'Other')], max_length=50)),
                ('standardized_value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('nic_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('bmc_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('bmc_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('core_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sockets', models.PositiveIntegerField(blank=True, null=True)),
                ('total_mem', models.PositiveIntegerField(blank=True, help_text='Total memory in GB', null=True)),
                ('mem_details', models.JSONField(blank=True, null=True)),
                ('disk_count', models.PositiveIntegerField(blank=True, null=True)),
                ('disk_details', models.JSONField(blank=True, null=True)),
                ('bios_version', models.CharField(blank=True, max_length=100, null=True)),
                ('bios_release_date', models.DateField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('kernel', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('assign_to', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login', models.CharField(blank=True, max_length=100, null=True)),
                ('user_folders', models.JSONField(blank=True, null=True)),
                ('accelerator', models.JSONField(blank=True, null=True)),
                ('network_interfaces', models.JSONField(blank=True, null=True)),
                ('expansion_slots', models.JSONField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=10)),
                ('pdu_connection', models.BooleanField(default=False)),
                ('data_source', models.CharField(blank=True, choices=[('manual', 'Manual'), ('discovery', 'Discovery'), ('import', 'Import'), ('api', 'API'), ('pull request', 'Pull Request')], max_length=20, null=True)),
                ('misc', models.JSONField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('is_public', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='overwatch.server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('network', models.CharField(max_length=18)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('reserved', 'Reserved'), ('quarantine', 'Quarantine')], default='available', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_assignments', to='overwatch.server')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='overwatch.subnet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
