# Generated by Django 6.0 on 2025-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0011_add_info_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='dhcp_pools',
            field=models.JSONField(blank=True, help_text='List of DHCP IP ranges (auto-calculated)', null=True),
        ),
        migrations.AddField(
            model_name='subnet',
            name='static_ip_pools',
            field=models.JSONField(blank=True, help_text="List of static IP ranges, e.g. ['10.0.1.1-10.0.1.50']", null=True),
        ),
    ]
