# Generated by Django 6.0 on 2025-12-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0012_subnet_dhcp_pools_subnet_static_ip_pools'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='device_type',
            field=models.CharField(blank=True, help_text='Device type: server, desktop, laptop, embedded, other', max_length=50, null=True),
        ),
    ]
