# Generated by Django 6.0 on 2025-12-10 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0013_server_device_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ipam',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipam',
            name='ip_type',
            field=models.CharField(choices=[('static', 'Static'), ('dhcp', 'DHCP')], default='static', max_length=20),
        ),
        migrations.AddField(
            model_name='ipam',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipam',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipam',
            name='active',
            field=models.BooleanField(default=True, help_text='Ping check - IP is responding'),
        ),
        migrations.AlterField(
            model_name='ipam',
            name='description',
            field=models.TextField(blank=True, help_text="Only editable when status is 'reserved'", null=True),
        ),
        migrations.AlterField(
            model_name='ipam',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='ipam',
            unique_together={('ip_address', 'subnet')},
        ),
        migrations.AddIndex(
            model_name='ipam',
            index=models.Index(fields=['subnet', 'status'], name='overwatch_i_subnet__b68370_idx'),
        ),
        migrations.AddIndex(
            model_name='ipam',
            index=models.Index(fields=['ip_address'], name='overwatch_i_ip_addr_18dbb1_idx'),
        ),
    ]
