# Generated by Django 6.0 on 2025-12-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0014_ipam_hostname_ipam_ip_type_ipam_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipam',
            name='is_bmc',
            field=models.BooleanField(default=False, help_text='Is this a BMC (Baseboard Management Controller) IP?'),
        ),
        migrations.AlterField(
            model_name='ipam',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reserved', 'Reserved'), ('quarantine', 'Quarantine')], default='available', max_length=20),
        ),
    ]
