# Generated by Django 6.0 on 2025-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0015_add_is_bmc_field_to_ipam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipam',
            name='ip_type',
            field=models.CharField(choices=[('static', 'Static'), ('dhcp', 'DHCP'), ('subnet_not_exist', 'Subnet Not Exist')], default='static', max_length=30),
        ),
    ]
