# Generated by Django 6.0 on 2025-12-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0016_update_ipam_ip_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipam',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reserved', 'Reserved'), ('quarantine', 'Quarantine'), ('conflict', 'Conflict')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipam',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='overwatch.subnet'),
        ),
    ]
