# Generated by Django 6.0 on 2025-12-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0017_alter_ipam_status_alter_ipam_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipam',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reserved', 'Reserved'), ('conflict', 'Conflict')], default='available', max_length=20),
        ),
    ]
