# Generated by Django 6.0 on 2025-12-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0018_alter_ipam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_by',
            field=models.CharField(choices=[('agent', 'Agent'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
    ]
