# Generated by Django 6.0 on 2025-12-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0020_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
