from django.urls import path

from . import views

app_name = "overwatch"

urlpatterns = [
    path("logs/", views.activity_log, name="activity_log"),
    path("logs/purge/", views.purge_old_audit_logs, name="purge_old_audit_logs"),
    path("dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("dashboard/api/data/", views.dashboard_data_api, name="dashboard_data_api"),
    path("", views.server_list, name="server_list"),
    path("servers/<int:pk>/", views.server_detail, name="server_detail"),
    path("servers/add/", views.server_create, name="server_create"),
    path("servers/<int:pk>/edit/", views.server_edit, name="server_edit"),
    path("servers/<int:pk>/delete/", views.server_delete, name="server_delete"),
    path("servers/<int:pk>/notes/add/", views.server_note_create, name="server_note_create"),
    path("servers/<int:pk>/notes/<int:note_pk>/edit/", views.server_note_edit, name="server_note_edit"),
    path("servers/<int:pk>/notes/<int:note_pk>/delete/", views.server_note_delete, name="server_note_delete"),
    path("dictionary/", views.dictionary_list, name="dictionary_list"),
    path("dictionary/add/", views.dictionary_create, name="dictionary_create"),
    path("dictionary/<int:pk>/edit/", views.dictionary_edit, name="dictionary_edit"),
    path("dictionary/<int:pk>/delete/", views.dictionary_delete, name="dictionary_delete"),
    path("dictionary/apply-translations/", views.dictionary_apply_translations, name="dictionary_apply_translations"),
    path("tags/", views.tag_list, name="tag_list"),
    path("tags/add/", views.tag_create, name="tag_create"),
    path("tags/<int:pk>/edit/", views.tag_edit, name="tag_edit"),
    path("tags/<int:pk>/delete/", views.tag_delete, name="tag_delete"),
    path("categories/", views.category_list, name="category_list"),
    path("categories/add/", views.category_create, name="category_create"),
    path("categories/<int:pk>/edit/", views.category_edit, name="category_edit"),
    path("categories/<int:pk>/delete/", views.category_delete, name="category_delete"),
    path("subnets/", views.subnet_list, name="subnet_list"),
    path("subnets/<int:pk>/", views.subnet_detail, name="subnet_detail"),
    path("subnets/add/", views.subnet_create, name="subnet_create"),
    path("subnets/<int:pk>/edit/", views.subnet_edit, name="subnet_edit"),
    path("subnets/<int:pk>/delete/", views.subnet_delete, name="subnet_delete"),
    path("ipam/", views.ipam_list, name="ipam_list"),
    path("ipam/add/", views.ipam_create, name="ipam_create"),
    path("ipam/<int:pk>/edit/", views.ipam_edit, name="ipam_edit"),
    path("ipam/<int:pk>/delete/", views.ipam_delete, name="ipam_delete"),
    path("ipam/<int:pk>/unreserve/", views.ipam_unreserve, name="ipam_unreserve"),
    path("ipam/available-ips/<int:subnet_id>/", views.ipam_available_ips, name="ipam_available_ips"),
    path("ipam/reserve/", views.ipam_reserve, name="ipam_reserve"),
    path("ipam/my-reserved-ips/", views.ipam_my_reserved_ips, name="ipam_my_reserved_ips"),
    path("ipam/release/", views.ipam_release_ips, name="ipam_release_ips"),
    path("overwatch/api/agent/data/", views.agent_data_push, name="agent_data_push"),
]
